---
# Service DNS will be "cva-management-center.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: cva-management-center
spec:
  selector:
    app: cva-management-center
  ports:
    - name: cva-management-center
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Only need 1 management-center
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cva-management-center
spec:
  selector:
    matchLabels:
      app: cva-management-center
  template:
    metadata:
      labels:
        app: cva-management-center
    spec:
      containers:
        - image: "eu.gcr.io/hazelcast-33/neilstevenson/cva-management-center"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          name: cva-management-center-container
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
---
