---
# Data loader, set arg for threshold (make it at least 20)
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cva-data-loader-site2
  name: cva-data-loader-site2
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: cva-data-loader-site2
    spec:
      containers:
        - env:
          - name: "MY_SITE"
            value: "site2"
          - name: "MY_THRESHOLD"
            value: "500"
          image: "hazelcast-cva/data-loader"
          imagePullPolicy: Never
          name: container-data-loader-site2
      restartPolicy: Never
---
