---
# Service DNS will be "cva-cpp.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: cva-cpp
spec:
  selector:
    app: cva-cpp
  ports:
  - port: 30001
    protocol: TCP
    targetPort: 30001
  type: LoadBalancer
---
# Creates 2 pods, for double performance, the minimum to prove scaling
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cva-cpp
spec:
  replicas: 2
  serviceName: cva-cpp
  selector:
    matchLabels:
      app: cva-cpp
  template:
    metadata:
      labels:
        app: cva-cpp
    spec:
      containers:
        - args: ["30001"]
          image: "hazelcast-platform-demos/cva-cpp"
          imagePullPolicy: Never
          name: cva-cpp-container
---
