---
# Service DNS will be "mancenter-service.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: management-center-service
spec:
  selector:
    app: cva-management-center
  ports:
    - name: management-center
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Only need 1 management-center
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cva-management-center
spec:
  selector:
    matchLabels:
      app: cva-management-center
  template:
    metadata:
      labels:
        app: cva-management-center
    spec:
      containers:
        - image: "hazelcast-cva/management-center"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          name: mancenter-container
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
---
