---
# Service DNS will be "cva-grafana.default.svc.cluster.local".
# Service DNS will be "cva-prometheus.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: cva-grafana
spec:
  selector:
    app: cva-grafana
  ports:
    - name: grafana
      port: 80
      targetPort: 80
    - name: graphite
      port: 2004
      targetPort: 2004
  type: LoadBalancer
---
# Service for Prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: cva-prometheus
spec:
  selector:
    app: cva-prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  type: LoadBalancer
---
# Only need 1 grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cva-grafana
spec:
  selector:
    matchLabels:
      app: cva-grafana
  template:
    metadata:
      labels:
        app: cva-grafana
    spec:
      containers:
        - image: "hazelcast-platform-demos/cva-grafana"
          imagePullPolicy: Never
          name: grafana-container
---
# Pods for Prometheus, only need one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cva-prometheus
spec:
  selector:
    matchLabels:
      app: cva-prometheus
  template:
    metadata:
      labels:
        app: cva-prometheus
    spec:
      containers:
        - image: "hazelcast-platform-demos/cva-prometheus"
          imagePullPolicy: Never
          name: prometheus-container
---
