{
 "title": "CVA Map stats",
 "description": "Map statistics for CVA clusters",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://hazelcast.com/files/brand-images/logo/hazelcast-logo-reverse.png\" width=\"360\" height=\"45\"></img></center>\n"
   }
  },
  {
   "title": "\"cva_trades\" map size",
   "type": "graph",
   "description": "IMap \"cva_trades\" in both clusters",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(hz_map_ownedEntryCount{mc_cluster='site1',name='cva_trades'})",
     "legendFormat": "site1.size",
     "target": "alias(max(hz_map_ownedEntryCount{mc_cluster='site1',name='cva_trades'}), 'site1.size')"
    },
    {
     "expr": "max(hz_map_ownedEntryCount{mc_cluster='site2',name='cva_trades'})",
     "legendFormat": "site2.size",
     "target": "alias(max(hz_map_ownedEntryCount{mc_cluster='site2',name='cva_trades'}), 'site2.size')"
    }
   ]
  },
  {
   "title": "\"cva_trades\" map usage",
   "type": "graph",
   "description": "IMap \"cva_trades\" in both clusters",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(hz_map_getCount{mc_cluster='site1',name='cva_trades'})",
     "legendFormat": "site1.reads",
     "target": "alias(max(hz_map_getCount{mc_cluster='site1',name='cva_trades'}), 'site1.reads')"
    },
    {
     "expr": "max(hz_map_putCount{mc_cluster='site1',name='cva_trades'})",
     "legendFormat": "site1.writes",
     "target": "alias(max(hz_map_putCount{mc_cluster='site1',name='cva_trades'}), 'site1.writes')"
    },
    {
     "expr": "max(hz_map_removeCount{mc_cluster='site1',name='cva_trades'})",
     "legendFormat": "site1.deletes",
     "target": "alias(max(hz_map_removeCount{mc_cluster='site1',name='cva_trades'}), 'site1.deletes')"
    },
    {
     "expr": "max(hz_map_setCount{mc_cluster='site1',name='cva_trades'})",
     "legendFormat": "site1.sets",
     "target": "alias(max(hz_map_setCount{mc_cluster='site1',name='cva_trades'}), 'site1.sets')"
    },
    {
     "expr": "max(hz_map_getCount{mc_cluster='site2',name='cva_trades'})",
     "legendFormat": "site2.reads",
     "target": "alias(max(hz_map_getCount{mc_cluster='site2',name='cva_trades'}), 'site2.reads')"
    },
    {
     "expr": "max(hz_map_putCount{mc_cluster='site2',name='cva_trades'})",
     "legendFormat": "site2.puts",
     "target": "alias(max(hz_map_putCount{mc_cluster='site2',name='cva_trades'}), 'site2.puts')"
    },
    {
     "expr": "max(hz_map_removeCount{mc_cluster='site2',name='cva_trades'})",
     "legendFormat": "site2.deletes",
     "target": "alias(max(hz_map_removeCount{mc_cluster='site2',name='cva_trades'}), 'site2.deletes')"
    },
    {
     "expr": "max(hz_map_setCount{mc_cluster='site2',name='cva_trades'})",
     "legendFormat": "site2.sets",
     "target": "alias(max(hz_map_setCount{mc_cluster='site2',name='cva_trades'}), 'site2.sets')"
    }
   ]
  },
  {
   "title": "\"cva_cp_cds\" map near-cache %age",
   "type": "graph",
   "description": "IMap \"cva_cp_cds\" in both clusters",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(hz_map_nearcache_hits{mc_cluster='site1',name='cva_cp_cds'}) * 100) / (sum(hz_map_nearcache_hits{mc_cluster='site1',name='cva_cp_cds'}) + sum(hz_map_nearcache_misses{mc_cluster='site1',name='cva_cp_cds'}) )",
     "legendFormat": "site1.near_cache_percent",
     "target": "alias(site1.GrafanaGlobalMetricsJob.map.cva_cp_cds.near_cache_percent, 'site1.near_cache_percent')"
    },
    {
     "expr": "(sum(hz_map_nearcache_hits{mc_cluster='site2',name='cva_cp_cds'}) * 100) / (sum(hz_map_nearcache_hits{mc_cluster='site2',name='cva_cp_cds'}) + sum(hz_map_nearcache_misses{mc_cluster='site2',name='cva_cp_cds'}) )",
     "legendFormat": "site2.near_cache_percent",
     "target": "alias(site2.GrafanaGlobalMetricsJob.map.cva_cp_cds.near_cache_percent, 'site2.near_cache_percent')"
    }
   ]
  },
  {
   "title": "\"cva_ircurves\" map size",
   "type": "graph",
   "description": "IMap \"cva_ircurves\" in both clusters",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(hz_map_ownedEntryCount{mc_cluster='site1',name='cva_ircurves'})",
     "legendFormat": "site1.size",
     "target": "alias(max(hz_map_ownedEntryCount{mc_cluster='site1',name='cva_ircurves'}), 'site1.size')"
    },
    {
     "expr": "max(hz_map_ownedEntryCount{mc_cluster='site2',name='cva_ircurves'})",
     "legendFormat": "site2.size",
     "target": "alias(max(hz_map_ownedEntryCount{mc_cluster='site2',name='cva_ircurves'}), 'site2.size')"
    }
   ]
  },
  {
   "title": "\"cva_ircurves\" map usage",
   "type": "graph",
   "description": "IMap \"cva_ircurves\" in both clusters",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(hz_map_getCount{mc_cluster='site1',name='cva_ircurves'})",
     "legendFormat": "site1.gets",
     "target": "alias(max(hz_map_getCount{mc_cluster='site1',name='cva_ircurves'}), 'site1.gets')"
    },
    {
     "expr": "max(hz_map_putCount{mc_cluster='site1',name='cva_ircurves'})",
     "legendFormat": "site1.puts",
     "target": "alias(max(hz_map_putCount{mc_cluster='site1',name='cva_ircurves'}), 'site1.puts')"
    },
    {
     "expr": "max(hz_map_removeCount{mc_cluster='site1',name='cva_ircurves'})",
     "legendFormat": "site1.deletes",
     "target": "alias(max(hz_map_removeCount{mc_cluster='site1',name='cva_ircurves'}), 'site1.deletes')"
    },
    {
     "expr": "max(hz_map_setCount{mc_cluster='site1',name='cva_ircurves'})",
     "legendFormat": "site1.sets",
     "target": "alias(max(hz_map_setCount{mc_cluster='site1',name='cva_ircurves'}), 'site1.sets')"
    },
    {
     "expr": "max(hz_map_getCount{mc_cluster='site2',name='cva_ircurves'})",
     "legendFormat": "site2.gets",
     "target": "alias(max(hz_map_getCount{mc_cluster='site2',name='cva_ircurves'}), 'site2.gets')"
    },
    {
     "expr": "max(hz_map_putCount{mc_cluster='site2',name='cva_ircurves'})",
     "legendFormat": "site2.puts",
     "target": "alias(max(hz_map_putCount{mc_cluster='site2',name='cva_ircurves'}), 'site2.puts')"
    },
    {
     "expr": "max(hz_map_removeCount{mc_cluster='site2',name='cva_ircurves'})",
     "legendFormat": "site2.deletes",
     "target": "alias(max(hz_map_removeCount{mc_cluster='site2',name='cva_ircurves'}), 'site2.deletes')"
    },
    {
     "expr": "max(hz_map_setCount{mc_cluster='site2',name='cva_ircurves'})",
     "legendFormat": "site2.sets",
     "target": "alias(max(hz_map_setCount{mc_cluster='site2',name='cva_ircurves'}), 'site2.sets')"
    }
   ]
  }
 ]
}