{
 "title": "Hazelcast Default",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(hz_cluster_size)", "legendFormat": "Member count" },
    {
     "expr": "round(max(hz_cluster_clock_clusterUpTime) / (1000 * 60))",
     "legendFormat": "Cluster uptime (minutes)"
    },
    { "expr": "max(hz_client_endpoint_count)", "legendFormat": "Client count" },
    {}
   ]
  },
  {
   "title": "Partition counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hz_partitions_activePartitionCount",
     "legendFormat": "Member {{mc_member}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hz_os_systemLoadAverage{mc_member=~\".+\"}",
     "legendFormat": "{{mc_member}}"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hz_memory_usedHeap{mc_member=~\".+\"} / (hz_memory_usedHeap{mc_member=~\".+\"} + hz_memory_freeHeap{mc_member=~\".+\"} ))*100",
     "legendFormat": "{{mc_member}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cache Hit Percentages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hz_cache_cacheHitPercentage", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Average operation times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hz_cache_averageGetTime", "legendFormat": "Get time {{name}}" },
    { "expr": "hz_cache_averagePutTime", "legendFormat": "Put time {{name}}" },
    { "expr": "hz_cache_averageRemovalTime", "legendFormat": "Removal time {{name}}" }
   ]
  },
  { "title": "Maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hz_map_ownedEntryMemoryCost / 1000  ",
     "legendFormat": "Owned entry mem. {{mc_member}}"
    },
    {
     "expr": "hz_map_backupEntryMemoryCost / 1000",
     "legendFormat": "Backup entry mem. {{mc_member}}"
    },
    { "expr": "hz_map_heapCost / 1000", "legendFormat": "Heap cost {{mc_member}}" }
   ]
  },
  {
   "title": "Average operation times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hz_map_totalGetLatency / ignoring(unit) hz_map_getCount",
     "legendFormat": "Get time {{mc_member}}"
    },
    {
     "expr": "hz_map_totalPutLatency / ignoring(unit) hz_map_putCount",
     "legendFormat": "Put time {{mc_member}}"
    },
    {
     "expr": "hz_map_totalRemoveLatency / ignoring(unit) hz_map_removeCount",
     "legendFormat": "Remove time {{mc_member}}"
    }
   ]
  },
  {
   "title": "Entry count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hz_map_entryCount", "legendFormat": "Owned entries {{mc_member}} " },
    { "expr": "hz_map_backupEntryCount  ", "legendFormat": "Backup entries {{mc_member}}" },
    { "expr": "hz_map_lockedEntryCount  ", "legendFormat": "Locked entries {{mc_member}}" },
    { "expr": "hz_map_dirtyEntryCount", "legendFormat": "Dirty entries: {{mc_member}}" }
   ]
  },
  {
   "title": "Nearcache Hit Percentages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hz_nearcache_hits / (hz_nearcache_hits + hz_nearcache_misses)",
     "legendFormat": "Cache hit %  {{mc_client}}"
    }
   ]
  }
 ]
}