{
 "title": "Hazelcast - \"@my.cluster1.name@\" cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://hazelcast.com/files/brand-images/logo/hazelcast-logo-reverse.png\" width=\"360\" height=\"45\"></img></center>\n"
   }
  },
  {
   "title": "Python sentiment output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hz_map_putCount{name=\"python_sentiment\"}[7m]))",
     "legendFormat": "WRITE RATE"
    }
   ]
  },
  {
   "title": "\"Put\" to maps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hz_map_putCount  " }
   ]
  },
  {
   "title": "Cluster size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hz_cluster_size" }
   ]
  }
 ]
}