---
# Service DNS will be "trade-monitor-hazelcast.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-hazelcast
spec:
  clusterIP: None
  selector:
    app: trade-monitor-hazelcast-node
  ports:
  - port: 5701
---
# Creates 2 pods, hazelcast-node-0 and hazelcast-node-1 in a stateful set.
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trade-monitor-hazelcast-node
spec:
  replicas: 2
  serviceName: trade-monitor-hazelcast
  selector:
    matchLabels:
      app: trade-monitor-hazelcast-node
  template:
    metadata:
      labels:
        app: trade-monitor-hazelcast-node
    spec:
      containers:
        - env:
          - name: "MY_BOOTSTRAP_SERVERS"
            value: "trade-monitor-kafka-broker-0.trade-monitor-kafka-broker.default.svc.cluster.local:9092,trade-monitor-kafka-broker-1.trade-monitor-kafka-broker.default.svc.cluster.local:9092,trade-monitor-kafka-broker-2.trade-monitor-kafka-broker.default.svc.cluster.local:9092"
          image: "hazelcast-platform-demos/trade-monitor-hazelcast-node"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
          name: hazelcast-node-container
          readinessProbe:
            httpGet:
              path: /hazelcast/health/ready
              port: 5701
            initialDelaySeconds: 30
