---
# Service DNS will be "trade-monitor-webapp.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-webapp
spec:
  selector:
    app: trade-monitor-webapp
  ports:
  - port: 8080
  type: NodePort
---
# Only need 1 webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-monitor-webapp
spec:
  selector:
    matchLabels:
      app: trade-monitor-webapp
  template:
    metadata:
      labels:
        app: trade-monitor-webapp
    spec:
      containers:
        - image: "hazelcast-trade-monitor/webapp"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          name: hazelcast-node-container
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
