---
# Runs 1 Zookeeper, 3 Kafka Brokers, creates a Kafka topic, and Kafdrop UI
---
############################################################################
# Services
############################################################################
---
# Kafdrop : DNS will be "trade-monitor-kafdrop-service.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-kafdrop-service
spec:
  selector:
    app: trade-monitor-kafdrop
  ports:
  - port: 8080
    targetPort: 9000
  type: NodePort
---
# Kafka Broker : DNS will be "trade-monitor-kafka-broker-service.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-kafka-broker-service
spec:
  clusterIP: None
  selector:
    app: trade-monitor-kafka-broker
  ports:
  - port: 9092
---
# Zookeeper : DNS will be "trade-monitor-zookeeper-service.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-zookeeper-service
spec:
  selector:
    app: trade-monitor-zookeeper
  ports:
  - port: 2181
  type: ClusterIP
---
############################################################################
# Deployments
############################################################################
---
# Kafdrop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kafdrop
  name: trade-monitor-kafdrop
spec:
  selector:
    matchLabels:
      app: trade-monitor-kafdrop
  template:
    metadata:
      labels:
        app: trade-monitor-kafdrop
        app.kubernetes.io/component: kafdrop
    spec:
      initContainers:
        - name: wait-for-pod-zookeeper
          image: busybox
          command: ['sh', '-c', 'sleep 300']
      containers:
        - env:
          - name: "KAFKA_BROKERCONNECT"
            value: "trade-monitor-kafka-broker-0.trade-monitor-kafka-broker-service.default.svc.cluster.local:9092,trade-monitor-kafka-broker-1.trade-monitor-kafka-broker-service.default.svc.cluster.local:9092,trade-monitor-kafka-broker-2.trade-monitor-kafka-broker-service.default.svc.cluster.local:9092"
          image: "hazelcast-trade-monitor/kafdrop"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /
              port: 9000
          name: kafdrop-container
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 30
---
# Zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: zookeeper
  name: trade-monitor-zookeeper
spec:
  selector:
    matchLabels:
      app: trade-monitor-zookeeper
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        app: trade-monitor-zookeeper
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
        - env:
          - name: "ALLOW_ANONYMOUS_LOGIN"
            value: "true"
          image: "hazelcast-trade-monitor/zookeeper"
          imagePullPolicy: Never
          name: zookeeper-container
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 2181
          name: zookeeper-container
          ports:
            - containerPort: 2181
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 2181
---
############################################################################
# Stateful Sets
############################################################################
---
# Kafka Broker, 3 pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/name: kafka
  name: trade-monitor-kafka-broker
spec:
  replicas: 3
  serviceName: trade-monitor-kafka-broker-service
  selector:
    matchLabels:
      app: trade-monitor-kafka-broker
  template:
    metadata:
      labels:
        app: trade-monitor-kafka-broker
        app.kubernetes.io/component: kafka
        app.kubernetes.io/name: kafka
    spec:
      initContainers:
        - name: wait-for-pod-zookeeper
          image: busybox
          command: ['sh', '-c', 'sleep 10']
      containers:
        - env:
          - name: "ALLOW_PLAINTEXT_LISTENER"
            value: "true"
          - name: "KAFKA_CFG_ZOOKEEPER_CONNECT"
            value: "trade-monitor-zookeeper-service.default.svc.cluster.local"
          - name: "MY_POD_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: "MY_POD_NAME"
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: "KAFKA_CFG_ADVERTISED_LISTENERS"
            value: "PLAINTEXT://$(MY_POD_NAME).trade-monitor-kafka-broker-service.default.svc.cluster.local:9092"
          - name: "POD_NAME"
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: "hazelcast-trade-monitor/kafka-broker"
          imagePullPolicy: Never
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 9092
          name: kafka-broker-container
          ports:
            - containerPort: 9092
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 9092
---
############################################################################
# Jobs
############################################################################
---
# Topic Create
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: job-topic-create
  name: job-topic-create
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: job-topic-create
    spec:
      initContainers:
        - name: wait-for-pod-kafka-broker
          image: busybox
          command: ['sh', '-c', 'sleep 240']
      containers:
        - env:
          - name: "MY_ZOOKEEPER"
            value: "trade-monitor-zookeeper-service.default.svc.cluster.local"
          image: "hazelcast-trade-monitor/topic-create"
          imagePullPolicy: Never
          name: container-job-topic-create
      restartPolicy: Never
---

