---
# OPTIONAL
# OPTIONAL
# OPTIONAL
# OPTIONAL
# OPTIONAL
# Open to allow remote client to connect from outside Kubernetes, eg. Desktop
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-grid-hazelcast-extra
spec:
  selector:
    app: trade-monitor-grid-hazelcast
  ports:
  - port: 5701
  type: LoadBalancer
---
