---
# Service DNS will be "trade-monitor-webapp.default.svc.cluster.local".
# Service DNS will be "mancenter-service.default.svc.cluster.local".
---
# Webapp
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-webapp
spec:
  selector:
    app: trade-monitor-webapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
---
# Only need 1 webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-monitor-webapp
spec:
  selector:
    matchLabels:
      app: trade-monitor-webapp
  template:
    metadata:
      labels:
        app: trade-monitor-webapp
    spec:
      containers:
        - image: "hazelcast-trade-monitor/webapp"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          name: webapp-container
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
---
# Management Center
---
apiVersion: v1
kind: Service
metadata:
  name: management-center-service
spec:
  selector:
    app: trade-monitor-management-center
  ports:
    - name: management-center
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Only need 1 management-center
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-monitor-management-center
spec:
  selector:
    matchLabels:
      app: trade-monitor-management-center
  template:
    metadata:
      labels:
        app: trade-monitor-management-center
    spec:
      containers:
        - image: "hazelcast-trade-monitor/management-center"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
          name: mancenter-container
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
---
