global:
  scrape_interval:     10s
  evaluation_interval: 10s
  
scrape_configs:
  - job_name: 'HZ MC'
    static_configs:
    - targets: ['@my.management.center.name@.default.svc.cluster.local:8080'] 
