global:
  scrape_interval:     10s
  evaluation_interval: 10s
  
scrape_configs:
  - job_name: 'HZ MC'
    static_configs:
    - targets: ['management-center-service.default.svc.cluster.local:8080'] 
