---
# Runs 1 Zookeeper, creates services for Kafka Brokers but not the brokers
# Also, 1 Pulsar to show as an alternative to Kakfa
---
############################################################################
# Services
############################################################################
---
# Kafka Broker : DNS will be "trade-monitor-kafka-broker.default.svc.cluster.local".
# FOR INTERNAL ACCESS: Eg. topic-create job
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-kafka-broker
spec:
  clusterIP: None
  selector:
    app: trade-monitor-kafka-broker
  ports:
  - port: 19092
---
# FOR EXTERNAL ACCESS: ONE EACH PER KAFKA BROKER
# "LoadBalancer" allows the ConfigMap to find all 3, needed for Webapp
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-kafka-broker-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: trade-monitor-kafka-broker-0
  ports:
  - port: 9092
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-kafka-broker-1
spec:
  selector:
    statefulset.kubernetes.io/pod-name: trade-monitor-kafka-broker-1
  ports:
  - port: 9092
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-kafka-broker-2
spec:
  selector:
    statefulset.kubernetes.io/pod-name: trade-monitor-kafka-broker-2
  ports:
  - port: 9092
  type: LoadBalancer
---
# Postgres : DNS will be "trade-monitor-postgres.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-postgres
spec:
  selector:
    app: trade-monitor-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: LoadBalancer
---
# Service for Pulsar
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-pulsar
spec:
  selector:
    app: trade-monitor-pulsar
  ports:
    - name: pulsar-scheme
      port: 6650
      targetPort: 6650
    - name: pulsar-http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Zookeeper : DNS will be "trade-monitor-zookeeper.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: trade-monitor-zookeeper
spec:
  selector:
    app: trade-monitor-zookeeper
  ports:
  - port: 2181
  type: ClusterIP
---
############################################################################
# Deployments
############################################################################
---
# Pod for Pulsar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-monitor-pulsar
spec:
  selector:
    matchLabels:
      app: trade-monitor-pulsar
  template:
    metadata:
      labels:
        app: trade-monitor-pulsar
    spec:
      containers:
        - image: "hazelcast-platform-demos/trade-monitor-pulsar"
          imagePullPolicy: Never
          name: trade-monitor-pulsar-container
---
# Zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: zookeeper
  name: trade-monitor-zookeeper
spec:
  selector:
    matchLabels:
      app: trade-monitor-zookeeper
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        app: trade-monitor-zookeeper
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
        - env:
          - name: "ALLOW_ANONYMOUS_LOGIN"
            value: "true"
          image: "hazelcast-platform-demos/trade-monitor-zookeeper"
          imagePullPolicy: Never
          name: zookeeper-container
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 2181
          name: trade-monitor-zookeeper-container
          ports:
            - containerPort: 2181
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 2181
---
