---
# Service DNS for Finos will be "transaction-monitor-FLAVOR-finos.default.svc.cluster.local".
# Service DNS for Flow will be "transaction-monitor-FLAVOR-flow.default.svc.cluster.local".
# Service DNS for Vector Search will be "transaction-monitor-FLAVOR-vector-search.default.svc.cluster.local".
# Service DNS for Webapp will be "transaction-monitor-FLAVOR-webapp.default.svc.cluster.local".
---
# FinOS - service defined in step 1
---
# Only need 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-monitor-FLAVOR-finos
spec:
  selector:
    matchLabels:
      app: transaction-monitor-FLAVOR-finos
  template:
    metadata:
      labels:
        app: transaction-monitor-FLAVOR-finos
    spec:
      containers:
        - image: "hazelcast-platform-demos/transaction-monitor-FLAVOR-finos"
          imagePullPolicy: Never
          name: transaction-monitor-FLAVOR-finos-container
          volumeMounts:
            - name: configmap
              mountPath: /customize/my-env.sh
              subPath: my-env.sh
      volumes:
        - name: configmap
          configMap:
            name: transaction-monitor-FLAVOR-configmap
            defaultMode: 0755
---
# Flow - service defined in step 1
---
# Only need 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-monitor-FLAVOR-flow
spec:
  selector:
    matchLabels:
      app: transaction-monitor-FLAVOR-flow
  template:
    metadata:
      labels:
        app: transaction-monitor-FLAVOR-flow
    spec:
      containers:
        - image: "hazelcast-platform-demos/transaction-monitor-FLAVOR-flow"
          imagePullPolicy: Never
          name: transaction-monitor-FLAVOR-flow-container
          volumeMounts:
            - name: configmap
              mountPath: /customize/my-env.sh
              subPath: my-env.sh
      volumes:
        - name: configmap
          configMap:
            name: transaction-monitor-FLAVOR-configmap
            defaultMode: 0755
---
# Vector Search - service defined in step 1
---
# Only need 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-monitor-FLAVOR-vector-search
spec:
  selector:
    matchLabels:
      app: transaction-monitor-FLAVOR-vector-search
  template:
    metadata:
      labels:
        app: transaction-monitor-FLAVOR-vector-search
    spec:
      containers:
        - image: "hazelcast-platform-demos/transaction-monitor-FLAVOR-vector-search"
          imagePullPolicy: Never
          name: transaction-monitor-FLAVOR-vector-search-container
          volumeMounts:
            - name: configmap
              mountPath: /customize/my-env.sh
              subPath: my-env.sh
      volumes:
        - name: configmap
          configMap:
            name: transaction-monitor-FLAVOR-configmap
            defaultMode: 0755
---
# Webapp - service defined in step 1
---
# Only need 1 webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-monitor-FLAVOR-webapp
spec:
  selector:
    matchLabels:
      app: transaction-monitor-FLAVOR-webapp
  template:
    metadata:
      labels:
        app: transaction-monitor-FLAVOR-webapp
    spec:
      containers:
        - env:
          - name: "MY_MYSQL_ADDRESS"
            value: "transaction-monitor-FLAVOR-mysql.default.svc.cluster.local:3306"
          image: "hazelcast-platform-demos/transaction-monitor-FLAVOR-webapp"
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
          name: transaction-monitor-FLAVOR-webapp-container
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
          volumeMounts:
            - name: configmap
              mountPath: /customize/my-env.sh
              subPath: my-env.sh
      volumes:
        - name: configmap
          configMap:
            name: transaction-monitor-FLAVOR-configmap
            defaultMode: 0755
---
