---
# Runs 1 Zookeeper, creates services for Kafka Brokers but not the brokers.
# Also, 1 Pulsar to show as an alternative to Kakfa
# Create services for anything accessed externally where it is useful as
# services take a while to provision, or more when the service IP is
# needed for the config map
---
############################################################################
# Services
############################################################################
---
# Kafka Broker : DNS will be "transaction-monitor-FLAVOR-kafka-broker.default.svc.cluster.local".
# FOR INTERNAL ACCESS: Eg. topic-create job
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-kafka-broker
spec:
  clusterIP: None
  selector:
    app: transaction-monitor-FLAVOR-kafka-broker
  ports:
  - port: 19092
---
# FOR EXTERNAL ACCESS: ONE EACH PER KAFKA BROKER
# "LoadBalancer" allows the ConfigMap to find all 3, needed for Webapp
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-kafka-broker-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: transaction-monitor-FLAVOR-kafka-broker-0
  ports:
  - port: 9092
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-kafka-broker-1
spec:
  selector:
    statefulset.kubernetes.io/pod-name: transaction-monitor-FLAVOR-kafka-broker-1
  ports:
  - port: 9092
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-kafka-broker-2
spec:
  selector:
    statefulset.kubernetes.io/pod-name: transaction-monitor-FLAVOR-kafka-broker-2
  ports:
  - port: 9092
  type: LoadBalancer
---
# Cassandra : DNS will be "transaction-monitor-FLAVOR-cassandra.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-cassandra
spec:
  selector:
    app: transaction-monitor-FLAVOR-cassandra
  ports:
  - port: 9042
    targetPort: 9042
  type: LoadBalancer
---
# FinOS : DNS will be "transaction-monitor-FLAVOR-finos.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-finos
spec:
  selector:
    app: transaction-monitor-FLAVOR-finos
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
# Flow : DNS will be "transaction-monitor-FLAVOR-flow.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-flow
spec:
  selector:
    app: transaction-monitor-FLAVOR-flow
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
# Maria : DNS will be "transaction-monitor-FLAVOR-maria.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-maria
spec:
  selector:
    app: transaction-monitor-FLAVOR-maria
  ports:
  - port: 3306
    targetPort: 3306
  type: LoadBalancer
---
# Mongo : DNS will be "transaction-monitor-FLAVOR-mongo.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-mongo
spec:
  selector:
    app: transaction-monitor-FLAVOR-mongo
  ports:
  - port: 27017
    targetPort: 27017
  type: LoadBalancer
---
# MySql : DNS will be "transaction-monitor-FLAVOR-mysql.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-mysql
spec:
  selector:
    app: transaction-monitor-FLAVOR-mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: LoadBalancer
---
# Postgres : DNS will be "transaction-monitor-FLAVOR-postgres.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-postgres
spec:
  selector:
    app: transaction-monitor-FLAVOR-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: LoadBalancer
---
# Service for Pulsar
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-pulsar
spec:
  selector:
    app: transaction-monitor-FLAVOR-pulsar
  ports:
    - name: pulsar-scheme
      port: 6650
      targetPort: 6650
    - name: pulsar-http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
# Vector Search : DNS will be "transaction-monitor-FLAVOR-vector-search.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-vector-search
spec:
  selector:
    app: transaction-monitor-FLAVOR-vector-search
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
# Webapp : DNS will be "transaction-monitor-FLAVOR-webapp.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-webapp
spec:
  selector:
    app: transaction-monitor-FLAVOR-webapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
---
# Zookeeper : DNS will be "transaction-monitor-FLAVOR-zookeeper.default.svc.cluster.local".
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-monitor-FLAVOR-zookeeper
spec:
  selector:
    app: transaction-monitor-FLAVOR-zookeeper
  ports:
  - port: 2181
  type: ClusterIP
---
############################################################################
# Deployments
############################################################################
---
# Pod for Pulsar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-monitor-FLAVOR-pulsar
spec:
  selector:
    matchLabels:
      app: transaction-monitor-FLAVOR-pulsar
  template:
    metadata:
      labels:
        app: transaction-monitor-FLAVOR-pulsar
    spec:
      containers:
        - image: "hazelcast-platform-demos/transaction-monitor-FLAVOR-pulsar"
          imagePullPolicy: Never
          name: transaction-monitor-FLAVOR-pulsar-container
---
# Zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: zookeeper
  name: transaction-monitor-FLAVOR-zookeeper
spec:
  selector:
    matchLabels:
      app: transaction-monitor-FLAVOR-zookeeper
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        app: transaction-monitor-FLAVOR-zookeeper
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
        - env:
          - name: "ALLOW_ANONYMOUS_LOGIN"
            value: "true"
          image: "hazelcast-platform-demos/transaction-monitor-FLAVOR-zookeeper"
          imagePullPolicy: Never
          name: zookeeper-container
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 2181
          name: transaction-monitor-FLAVOR-zookeeper-container
          ports:
            - containerPort: 2181
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 2181
---
