############################################################################
# Jobs
############################################################################
---
# Transaction Producer
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: transaction-monitor-FLAVOR-job-trans-producer
  name: transaction-monitor-FLAVOR-job-trans-producer
spec:
  template:
    metadata:
      labels:
        app: transaction-monitor-FLAVOR-job-trans-producer
    spec:
      containers:
        - env:
          # Internal port 19092
          - name: "MY_BOOTSTRAP_SERVERS"
            value: "transaction-monitor-FLAVOR-kafka-broker-0.transaction-monitor-FLAVOR-kafka-broker.default.svc.cluster.local:19092,transaction-monitor-FLAVOR-kafka-broker-1.transaction-monitor-FLAVOR-kafka-broker.default.svc.cluster.local:19092,transaction-monitor-FLAVOR-kafka-broker-2.transaction-monitor-FLAVOR-kafka-broker.default.svc.cluster.local:19092"
          # Default port
          - name: "MY_PULSAR_ADDRESS"
            value: "transaction-monitor-FLAVOR-pulsar.default.svc.cluster.local"
          image: "hazelcast-platform-demos/transaction-monitor-FLAVOR-transaction-producer"
          imagePullPolicy: Never
          name: transaction-monitor-FLAVOR-job-trans-producer-container
      restartPolicy: Never
